export const SET_USER_NAME = 'REGISTER::SET_USER_NAME';
export const SET_EMAIL = 'REGISTER::SET_EMAIL';
export const SET_PASSWORD = 'REGISTER::SET_PASSWORD';
export const SET_PASSWORD_CONFIRM = 'REGISTER::SET_PASSWORD_CONFIRM';